### ISSUE TITLE
Error in the acknowledgements

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-sample-id-metadata#1]
Emily Robles is incorrectly acknowledged as part of BNL in the README.
(Is using "Issues" the best way of advising of these kinds of small changes? I'm not fully up to speed on the real power of Git yet. This is more of a test than a real issue).

**Comment by wavingtowaves** [comment]
Thanks @regnans ! And yeah good to test out the systems.  

As you can see from my updates to this issue, I've assigned it to Joan and labeled it as a 'typo.' You should be able to do this for any issues you get on the gas-exchange repo since you are admin on that.  Assigning issues and tagging them helps prioritize the work on the page. We'll update the README.md file to fix this.

And yes, once the files are up on GitHub issues will the way to track even the small changes.  We can fix them quick and close them, and then they'll no longer appear as an open "issue".

**Comment by wavingtowaves** [comment]
@JEDamerow Should we move Emily's name to another part of the acknowledgements section? Or just make sure Emily is removed from BNL section?

Link to the section here: https://github.com/ess-dive-community/essdive-sample-id-metadata#funding-and-acknowledgements

**Comment by regnans** [comment]
@JEDamerow further correct to this. Brookhaven does not have an SFA. This acknowledgement is incorrect. 

Please delete: 
Brookhaven National Lab TES SFA, Next Generation Ecosystem Experiments (NGEE) Tropics: Kim Ely, Emily Robles

I'd suggest updating the text to:
Next Generation Ecosystem Experiments -Arctic (NGEE-Arctic) and -Tropics (NGEE-Tropics) projects: Kim Ely 

Or, to also mention Brookhaven: 
Next Generation Ecosystem Experiments -Arctic (NGEE-Arctic) and -Tropics (NGEE-Tropics) projects: Kim Ely, Brookhaven National Laboratory

thanks, Kim

**Comment by JEDamerow** [comment]
@regnans Ok, just corrected. Thanks for pointing this out.

**Comment by wavingtowaves** [comment]
Going to close the issue, thanks @regnans for identifying issue and @JEDamerow for fixing.
